import Head from "next/head";
import useSWR from "swr";

import { Inter } from "@next/font/google";

import TrendingMovies from "../components/movies/TrendingMovies";
import PopularMovies from "../components/movies/PopularMovies";
import NowPlayingMovies from "../components/movies/NowPlayingMovies";
import UpcomingMovies from "../components/movies/UpcomingMovies";
import TopRatedMovies from "../components/movies/TopRatedMovies";
import TrendingTV from "../components/tv/TrendingTV";
import PopularTV from "../components/tv/PopularTV";
import AiringTodayTV from "../components/tv/AiringTodayTV";
import OnAirTV from "../components/tv/OnAirTV";
import TopRatedTV from "../components/tv/TopRatedTV";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Entertainment Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* Movies */}

      <TrendingMovies />

      <PopularMovies />

      <NowPlayingMovies />

      <UpcomingMovies />

      <TopRatedMovies />

      {/* TV Series */}
      <TrendingTV />

      <PopularTV />

      <AiringTodayTV />

      <OnAirTV />

      <TopRatedTV />

      <div>
        <div></div>
      </div>
    </>
  );
}
